name: CI BrainLife App Tests

# 1. Déclencheurs : Quand lancer les tests ?
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest # On utilise un serveur Linux standard

    outputs:
      status: ${{ job.status }}

    steps:
    # Étape A : Copier le code de ton dépôt sur le serveur GitHub
    - name: Récupération du code (Checkout)
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Étape B : Installer Python
    - name: Configuration de Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Version stable pour MNE et Pytest

    # Étape C : Installer les outils nécessaires
    - name: Installation des dépendances
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    # Étape D : Lancer ton fameux script de test
    - name: Exécution des scénarios Pytest
      run: |
        docker run --rm -v "$(pwd)":/workspace -w /workspace aunnikri642/app-freesurfer-mne-source-recon:latest python -m pytest tests/test_main.py -v